name: On Discuss

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  discussions: write

jobs:
  discuss:
    uses: link-seek/issue-resolver-l1/.github/workflows/discuss.yml@main
    secrets: inherit
